module.exports = {
	docs: {
		'Getting Started': [
			'welcome',
			'eightshift-libs',
			'eightshift-frontend-libs-tailwind',
			'eightshift-frontend-libs',
			'requirements',
			'versions',
			'theme',
			'plugin',
		],
		Basics: [
			'basics/basics-intro',
			'basics/wp-cli',
			'basics/architecture-concepts',
			{
				type: 'category',
				label: 'Backend',
				items: [
					'basics/backend',
					'basics/namespaces',
					'basics/extending-classes',
					'basics/autowiring',
					'basics/example-class',
					'basics/manifest',
					{
						type: 'category',
						label: 'Rest',
						items: ['basics/rest', 'basics/rest-field', 'basics/rest-route'],
					},
				],
			},
			{
				type: 'category',
				label: 'Frontend',
				items: [
					'basics/frontend',
					'basics/webpack',
					'basics/library',
					'basics/global-settings',
					'basics/writing-styles',
					'basics/fonts',
					'basics/dynamic-import',
				],
			},
			{
				type: 'category',
				label: 'Blocks',
				items: [
					'basics/blocks',
					'basics/blocks-important',
					'basics/blocks-faq',
					'basics/blocks-registration',
					'basics/blocks-structure',
					'basics/blocks-global-manifest',
					'basics/block-structure',
					'basics/blocks-component-structure',
					'basics/block-manifest',
					'basics/blocks-component-manifest',
					'basics/blocks-attributes',
					'basics/blocks-component-in-block',
					'basics/blocks-wrapper',
					'basics/blocks-variations',
					'basics/blocks-patterns',
					'basics/blocks-transforms',
					'basics/blocks-hooks',
					'basics/blocks-special-use-cases',
					'basics/blocks-reusable',
					'basics/blocks-styles',
					'basics/blocks-storybook',
				],
			},
			{
				type: 'category',
				label: 'Helpers',
				items: ['basics/helpers', 'basics/helpers-javascript', 'basics/helpers-scss', 'basics/helpers-php'],
			},
			'basics/tips-tricks',
			{
				type: 'category',
				label: 'TailwindCSS',
				items: ['tailwind/intro', 'tailwind/getting-started', 'tailwind/manifest', 'tailwind/helpers'],
			},
		],
		Tutorials: ['tutorials/intro'],
		Migrations: [
			'migrations/14-15',
			'migrations/13-14',
			'migrations/12-13',
			'migrations/11-12',
			'migrations/10-11',
			'migrations/9-10',
			'migrations/8-9',
			'migrations/7-8',
			'migrations/6-7',
			'migrations/5-6',
		],
		'Additional Libraries': [
			'additional-libraries/boilerplate',
			'additional-libraries/boilerplate-plugin',
			'additional-libraries/frontend-libs-tailwind',
			'additional-libraries/frontend-libs',
			'additional-libraries/libs',
			'additional-libraries/forms',
			'additional-libraries/docs',
			'additional-libraries/coding-standards',
		],
	},
};
